---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by admin.
--- DateTime: 2020/4/15 14:46
---
require "Character.CharacterCommon"
local CharacterUtil = {}
function CharacterUtil.FindCharacterHand(object, data)
    local childern = object:GetComponentsInChildren(typeof(CS.UnityEngine.Transform))
    local count = childern.Length - 1
    for i = 0, count do
        local child = childern[i];
        for _, v in pairs(CharacterHandPoint) do
            if child.name == v then
                data[child.name] = child
            end
        end
    end
end

return CharacterUtil