---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by admin.
--- DateTime: 2020/4/10 14:33
---

local Character = BaseClass("Character", TransformObject)

local function __init(self)
    --战斗id
    self.fighterId = nil
    --龙骨模型
    self.shape = nil

    --朝向
    self.worldDir = nil
    --坐标
    self.worldPos = nil
    self.speed = nil
    self.layer = SceneLayer.Character

    --加载模型标志位
    self.initResourceOk = false
    self.inited = false

    --角色创建好了后,是否显示隐藏
    self.hide = false

    --  名字，血条， 特效，代理
    self.hudAgent = nil

    self.root = nil
    -- 加载后的资源
    self.pfb = nil
    -- 模型
    self.model = nil
    self.modelName = nil

    -- 角色资源加载回调
    self.resourceCallBack = nil

    self.actionConttroller = nil


end

local function Initialize(self, shape, pos, dir, callback)
    self.shape = shape
    self.worldPos = pos
    self.worldDir = dir
    self.resourceCallBack = callback
    if self.inited then
        return ;
    end
    self.hudAgent = require "Logic.Character.HudAgent".New(self)
    local fullPath = "" .. shape
    -- 加载
    GameObjectPool:GetInstance():GetGameObjectAsync(fullPath, BindCallback(self, self.CharacterLoadedEnd))
    self.inited = true
end

local function CharacterLoadedEnd(self, pfb)
    if IsNull(pfb) then
        return
    end
    self.pfb = pfb
    pfb.transform.position = Vector3.zero
    pfb.transform:SetParent(self.transform, false)
    self.model = require "Character.Model.Model".New(self)
    self.initResourceOK = true


    -- self.hide为false表示默认不隐藏
    self:SetVisible(self.hide)

    self:RefreshCharacterView()
    if self.resourceCallBack then
        self.resourceCallBack()
    end
end

-- 刷新所外形相关数据
local function RefreshCharacterView(self)
    if not self.model then
        return
    end

    if self.hudAgent then
        self:RefreshHudView()
    end

    self:UpdateLayer()

end

local function RefreshHudView(self)

end

local function UpdateLayer()
    if not (self.initResourceOK) then
        return
    end

    self.gameObject.layer = self:GetLayer();
    local components = self.gameObject:GetComponentsInChildren(CS.UnityEngine.Transform);
    local length = components.Length - 1;
    for i = 0, length do
        components[i].gameObject.layer = self.layer;
    end
end

Character.__init = __init
Character.Initialize = Initialize
Character.CharacterLoadedEnd = CharacterLoadedEnd
Character.RefreshCharacterView = RefreshCharacterView
Character.RefreshHudView = RefreshHudView
Character.UpdateLayer = UpdateLayer
return Character