---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ricashao.
--- DateTime: 2020/4/16 18:16
---
local BattleShowUnit = BaseClass("BattleShowUnit", Singleton)

local function __init(self)
    self.showUnitData = nil
    self.finishCallBack = nil
    self.showType = BattleShowRound.NoSkill
    self.curBattleSkill = nil

    self.skillActionEnd = false
    self.skillHitEnd = false

    self.curExecute = nil
    self.curNewFighter = {}
    self.curUnitResult = {}
    -- k v
    self.curRoleAttribute = {}
end

local function StartShowUnit(self, showUnitData, cb)
    self:Clear()
    self.showUnitData = showUnitData
    self.finishCallBack = cb
    self:Parse(showUnitData)
    self:BuildBattleShowUnit()
end

local function Parse(self, data)
    local curExecute = require "Battle.Show.Data.RoundExecute".New();
    curExecute:Parse(data.execute)
    self.curExecute = curExecute

    if (data.newfighter) then
        -- 战斗添加新Npc
        for k, v in pairs(data.newfighter) do
            local battler = require "Battle.Battler.Battler".New()
            battler:Parse(v)
            table.insert(self.curNewFighter, battler)
        end
    end

    if (data.resultlist) then
        -- 战斗结果
        for k, v in pairs(data.resultlist) do
            local result = require "Battle.Show.Data.RoundResultUnit".New();
            result:Parse(v);
            table.insert(M.curUnitResult, result);
        end
    end

    -- 战斗脚本接收者，此动作后属性的变化
    for k, v in pairs(data.rolechangedattrs) do
        M.curRoleAttribute[k] = v;
    end

    -- 战斗脚本接收者的宠物，此动作后属性的变化
    for k, v in pairs(data.petchangedattrs) do
        M.curPetAttribute[k] = v;
    end
end


--清理上回合表现数据
local function Clear(self)
    self.showUnitData = nil
    self.finishCallBack = nil
    self.curBattleSkill = nil
    self.curNewFighter = {}
    self.curUnitResult = {}
    self.curRoleAttribute = {}
    self.showType = BattleShowRound.NoSkill
    self.skillActionEnd = false
    self.skillHitEnd = false
end

BattleShowUnit.__init = __init
BattleShowUnit.StartShowUnit = StartShowUnit
BattleShowUnit.Clear = Clear
BattleShowUnit.Parse = Parse
return BattleShowUnit