---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ricashao.
--- DateTime: 2020/5/1 11:06
---
local SkillContext = BaseClass("SkillContext")

local function __init(self)
    self.cid = 0
    self.tid = 0
    self.caster = nil --施法者
    self.targets = {} --目标列表
    self.skillConfig = nil --技能配置
    self.unitResult = nil --技能结果集
end

SkillContext.__init = __init

return SkillContext