---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ricashao.
--- DateTime: 2020/4/19 1:23
---
local BattleSkill = BaseClass("BattleSkill")

local SkillShowType = {}
SkillShowType.Normal = 1
SkillShowType.Illusion = 2

local function InitBasicCfg(self)
    self.battler = BattleManager:GetInstance():GetBattle():FindBattlerByID(self.battlerId)
end

local function __init(self, battlerId, aimId, skillId, execute, unitResult, endCallback)
    self.battlerId = battlerId
    self.aimId = aimId
    self.skillId = skillId
    --是否是循环技能
    self.isLoop = false
    self.showSkillType = SkillShowType.Normal
    self.execute = execute
    self.unitResult = unitResult
    self.endCallback = endCallback

    InitBasicCfg(self)
end

BattleSkill.__init = __init
return BattleSkill