--Generated By protoc-gen-lua Do not Edit
local protobuf = require "Framework.Net.Protobuf.protobuf"
local common_pb = require("Net.Protol.common_pb")
local _M = {}

_M.TESTBATTLE_C2S_MSG = protobuf.Descriptor();
_M.TESTBATTLE_S2C_MSG = protobuf.Descriptor();
_M.TESTBATTLE_S2C_MSG_BATTLEPLAY_FIELD = protobuf.FieldDescriptor();

_M.TESTBATTLE_C2S_MSG.name = "TestBattle_C2S_Msg"
_M.TESTBATTLE_C2S_MSG.full_name = ".TestBattle_C2S_Msg"
_M.TESTBATTLE_C2S_MSG.nested_types = {}
_M.TESTBATTLE_C2S_MSG.enum_types = {}
_M.TESTBATTLE_C2S_MSG.fields = {}
_M.TESTBATTLE_C2S_MSG.is_extendable = false
_M.TESTBATTLE_C2S_MSG.extensions = {}
_M.TESTBATTLE_S2C_MSG_BATTLEPLAY_FIELD.name = "battlePlay"
_M.TESTBATTLE_S2C_MSG_BATTLEPLAY_FIELD.full_name = ".TestBattle_S2C_Msg.battlePlay"
_M.TESTBATTLE_S2C_MSG_BATTLEPLAY_FIELD.number = 1
_M.TESTBATTLE_S2C_MSG_BATTLEPLAY_FIELD.index = 0
_M.TESTBATTLE_S2C_MSG_BATTLEPLAY_FIELD.label = 1
_M.TESTBATTLE_S2C_MSG_BATTLEPLAY_FIELD.has_default_value = false
_M.TESTBATTLE_S2C_MSG_BATTLEPLAY_FIELD.default_value = nil
_M.TESTBATTLE_S2C_MSG_BATTLEPLAY_FIELD.message_type = common_pb.SENDBATTLEPLAY
_M.TESTBATTLE_S2C_MSG_BATTLEPLAY_FIELD.type = 11
_M.TESTBATTLE_S2C_MSG_BATTLEPLAY_FIELD.cpp_type = 10

_M.TESTBATTLE_S2C_MSG.name = "TestBattle_S2C_Msg"
_M.TESTBATTLE_S2C_MSG.full_name = ".TestBattle_S2C_Msg"
_M.TESTBATTLE_S2C_MSG.nested_types = {}
_M.TESTBATTLE_S2C_MSG.enum_types = {}
_M.TESTBATTLE_S2C_MSG.fields = {_M.TESTBATTLE_S2C_MSG_BATTLEPLAY_FIELD}
_M.TESTBATTLE_S2C_MSG.is_extendable = false
_M.TESTBATTLE_S2C_MSG.extensions = {}

_M.TestBattle_C2S_Msg = protobuf.Message(_M.TESTBATTLE_C2S_MSG)
_M.TestBattle_S2C_Msg = protobuf.Message(_M.TESTBATTLE_S2C_MSG)

return _M