---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2020/3/29 14:30
---

local CameraStayState = BaseClass("CameraStayState", CameraState)

local function __init(self)
    self.stateType = CameraState.Stay
end

CameraStayState.__init = __init
return CameraStayState