---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2020/3/29 14:34
---
local CameraFollowState = BaseClass("CameraFollowState", CameraState)

local function __init(self)
    self.stateType = CameraState.Follow;
    self.target = nil;
    self.targetPos = nil;
    self.factor = 6;
end

local function LateTick(self, delta, context, camera)
    if not camera then
        return ;
    end

    self.target = camera:GetFollowTarget();

    if (not self.target) then
        return ;
    end

    if (not self.target:GetInitResourceResult()) then
        return ;
    end

    if (not self.target:GetMoveAgent()) or (self.target:GetMoveAgent():IsStop()) then
        return ;
    end

    self.targetPos = self.target:GetWorldPosition() + camera.offset;
    local curPos = camera.transform.position;

    local dir = self.targetPos - curPos;
    camera.transform.position = (dir * delta) * self.factor + curPos;
end

CameraFollowState.__init = __init
CameraFollowState.LateTick = LateTick

return CameraFollowState