---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2020/3/29 14:16
---
local CameraState = BaseClass("CameraState")
CameraState = {
    Invalid = 0,
    Stay = 1,
    Follow = 2,
}

local function __init(self)
    self.stateType = CameraState.Invalid
end

local function Enter(self, context, camera)
end

local function LateTick(self, delta, context, camera)
end

local function Exit(self, context, camera)
end

local function GetStateName(self)
    return self.stateType
end

CameraState.__init = __init
CameraState.Enter = Enter
CameraState.LateTick = LateTick
CameraState.Exit = Exit
CameraState.GetStateName = GetStateName

return CameraState;