---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ricashao.
--- DateTime: 2020/4/16 13:26
---
local AIBeforeEndState = BaseClass("AIBeforeEndState", BaseState)

---Enter
---@param self table
---@param context table
local function Enter(self, context)
    --todo AI
    context:TriggerEvent(BattleStateEvent.BattleEnd)
end

local function TriggerEvent(self, eventName, context)
    --结束前AI -> 战斗结束
    if (eventName == BattleStateEvent.BattleEnd) then
        context:SetStateByName(BattleState.eBattleStateEnd)
    end
end

local function GetStateName(self)
    return BattleState.eBattleStateAIBeforeBattleEnd
end

AIBeforeEndState.GetStateName = GetStateName
AIBeforeEndState.Enter = Enter
AIBeforeEndState.TriggerEvent = TriggerEvent
return AIBeforeEndState