---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2020/4/16 7:59
---
local AIBeforeShowState = BaseClass("AIBeforeShowState", BaseState)


return AIBeforeShowState