---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ricashao.
--- DateTime: 2020/4/16 7:59
---
local AIBeforeShowState = BaseClass("AIBeforeShowState", BaseState)

local function Enter(self, context)
    local aiAction = BattleManager:getInstance():GetBattle():GetAIActionBeforeOpearte()
    if (aiAction == nil or table.length(aiAction) == 0) then
        context:TriggerEvent(BattleStateEvent.BattleShow)
    end
    BattleManager:getInstance():GetBattle():DealAIAction(aiAction)
end

local function TriggerEvent(eventName, context)
    --- 回合前AI -> 战斗演示
    if (eventName == BattleStateEvent.BattleShow) then
        context.setStateByName(BattleState.eBattleStateShow)
    end
end

local function GetStateName(self)
    return BattleState.eBattleStateAIBeforeShow
end

AIBeforeShowState.Enter = Enter
AIBeforeShowState.GetStateName = GetStateName
AIBeforeShowState.TriggerEvent = TriggerEvent

return AIBeforeShowState