---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2020/4/15 23:53
---

local BaseState = BaseClass("BaseState")

local function Enter(self, context)
end

local function Tick(self, delta, context)
end

local function Leave(self, context)
end

local function TriggerEvent(self, eventName, context)
end

local function GetStateName(self)
    return BattleState.eBattleStateNull
end

BaseState.Enter = Enter
BaseState.Tick = Tick
BaseState.Leave = Leave
BaseState.TriggerEvent = TriggerEvent
BaseState.GetStateName = GetStateName

return BaseState