---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ricashao.
--- DateTime: 2020/4/16 13:36
---
local BeginState = BaseClass("BeginState", BaseState)

local function GetStateName(self)
    return BattleState.eBattleStateBegin
end

local function TriggerEvent(self, eventName, context)
    -- 开始战斗 -> 操作前AI
    if (eventName == BattleStateEvent.BattleBeforeAI) then
        context:SetStateByName(BattleState.eBattleStateAIBeforeShow)
    end

    -- 开始战斗 -> 战斗演示
    if (eventName == BattleStateEvent.BattleShow) then
        context:SetStateByName(BattleState.eBattleStateShow)
    end

    -- 开始战斗 -> 战斗结束AI
    if (eventName == BattleStateEvent.BattleAIBeforeEnd) then
        context:SetStateByName(BattleState.eBattleStateAIBeforeBattleEnd)
    end
end

BeginState.GetStateName = GetStateName
BeginState.TriggerEvent = TriggerEvent
return BeginState