---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ricashao.
--- DateTime: 2020/4/16 13:40
---
local EndState = BaseClass("EndState", BaseState)

local function Enter(self, context)
    --todo 显示结果界面
end

local function GetStateName(self)
    return BattleState.eBattleStateEnd
end

EndState.GetStateName = GetStateName
EndState.Enter = Enter
return EndState