---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by admin.
--- DateTime: 2020/4/16 13:42
---
local ShowState = BaseClass("ShowState", BaseState)

local function Enter(self, context)
    BattleManager:GetInstance():GetBattle():GetBattleShow():StartBattleShow()
end

local function GetStateName(self)
    return BattleState.eBattleStateShow
end

local function TriggerEvent(self, eventName, context)
    --战斗演示 -> 等待回合结束
    if (eventName == BattleStateEvent.BattleWaitEnd) then
        context:SetStateByName(BattleState.eBattleStateWaitEnd)
    end

    --战斗演示 -> 战斗演示 （特殊 卡回合了??? 异常处理）
    if (eventName == BattleStateEvent.BattleShow) then
        context:SetStateByName(BattleState.eBattleStateShow)
    end

    --战斗演示 -> 战斗结束前AI
    if (eventName == BattleStateEvent.BattleAIBeforeEnd) then
        context:SetStateByName(BattleState.eBattleStateAIBeforeBattleEnd)
    end

    if (eventName == BattleStateEvent.BattleBeforeAI) then
        context:SetStateByName(BattleState.eBattleStateAIBeforeShow)
    end
end

ShowState.GetStateName = GetStateName
ShowState.Enter = Enter
ShowState.TriggerEvent = TriggerEvent
return ShowState