---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ricashao.
--- DateTime: 2020/4/16 13:48
---
local WaitEndState = BaseClass("WaitEndState", BaseState)

local function Enter(self, context)
    BattleManager:GetInstance():PlayNextRound()
end

local function TriggerEvent(self, eventName, context)
    --等待回合结束 -> 回合前AI
    if (eventName == BattleStateEvent.BattleBeforeAI) then
        context:SetStateByName(BattleState.eBattleStateAIBeforeShow)
    end
    --等待回合结束 -> 战斗演示
    if (eventName == BattleStateEvent.BattleShow) then
        context:SetStateByName(BattleState.eBattleStateShow)
    end
    --等待回合结束 -> 战斗结束前AI
    if (eventName == BattleStateEvent.BattleAIBeforeEnd) then
        context:SetStateByName(BattleState.eBattleStateAIBeforeBattleEnd)
    end
end

local function GetStateName(self)
    return BattleState.eBattleStateWaitEnd
end

WaitEndState.GetStateName = GetStateName
WaitEndState.Enter = Enter
WaitEndState.TriggerEvent = TriggerEvent
return WaitEndState