---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2020/4/17 22:24
---
local AttackAction = BaseClass("AttackAction", GUnitAction)
AttackAction._creators = nil

function AttackAction.GetCreator(id)
    if (AttackAction._creators) then
        AttackAction._creators["1"] = require "Battle.Skills.Operator.Op1"
    end
end

local function Create(self, context)
    --设置动作
    self._action = UnitActionManager:GetInstance():GetAction(context.skillConfig.action)
    self._ac = AniController:GetInstance()
    self.context = context
end

function AttackAction.GetOperator(id, context)
    local creator = AttackAction.GetCreator(id)
    if (not creator) then
        creator = AttackAction.GetCreator("1")
    end
    local action = creator.New()
    Create(action, context)
    return action
end

local function CanStop(self)
    return self._isEnd
end

local function DispatchEvent(self, unit, eventType)
    self:OnFire(self.context)
end

--播放动作
local function Start(self, unit, has, callback)
    local cunit = context.caster
    if (not cunit) then
        return
    end
    self.finalCallBack = callback
    local tunit = context.mainTarget
    if (tunit) then
        if (cunit ~= tunit) then
            cunit:ChangeFace(FaceToUtils.GetFaceTo4(cunit.x, cunit.y, tunit.x, tunit.y, unit:FaceTo()))
        end
    end

    local cfg = context.skillConfig
    if (cfg and cfg.casterEf ~= "") then
        --起手施法动画    
    end
    self:Fire(self.context)
end

local function Fire(self, context)

end

local function OnFire(self, context)

end

AttackAction.OnFire = OnFire
AttackAction.Fire = Fire
AttackAction.Start = Start
AttackAction.DispatchEvent = DispatchEvent
AttackAction.CanStop = CanStop
AttackAction.OnFire = OnFire
return AttackAction