---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ricashao.
--- DateTime: 2020/4/16 23:52
---
local UnitAction = require "Unit.UnitAction"
local GUnitAction = BaseClass("GUnitAction", UnitAction)

local function __init(self)
    self._action = nil
end

local function GetAction(self, mountType)
    return self._action
end

GUnitAction.__init = __init
GUnitAction.GetAction = GetAction
return GUnitAction