---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ricashao.
--- DateTime: 2020/4/16 23:52
---
local UnitAction = require "Unit.UnitAction"
local GUnitAction = BaseClass("GUnitAction", UnitAction)



return GUnitAction