---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2020/3/28 21:43
---
local CameraManager = BaseClass("CameraManager", Singleton)

local function __init(self)
    self.mainCamera = nil
end

function CameraManager.SetCamera(self, followTarget, cameraData)
    --Set Camera
    if self.mainCamera == nil then
        self.mainCamera = require "Camera.MainCamera.SmartCamera".New()
        self.mainCamera:SetCamera(Camera.main)
        --Camera.main.gameObject:AddComponent(CutImage.GetClassType())
        --local cutImage = Camera.main.gameObject:GetComponent(CutImage.GetClassType())
        --self.mainCamera.cutImageAgent = cutImage
        require "Camera.CameraContext":GetInstance():SetCameraTarget(self.mainCamera)

        CS.UnityEngine.Object.DontDestroyOnLoad(self.mainCamera.gameObject)
    end
    self:SetCameraAttribute(followTarget, cameraData)
end

local function GetSmartCamera(self)
    return self.mainCamera
end

-- 设置相机参数
local function SetCameraAttribute(self, followTarget, cameraData)
    local mainCamera = self.mainCamera
    if (not mainCamera) then
        return
    end

    if cameraData then
        local rotation = Quaternion.Euler(cameraData.camerarot_x, cameraData.camerarot_y, cameraData.camerarot_z)
        mainCamera:RotateToQua(rotation)
        mainCamera:SetFov(cameraData.fov)
        mainCamera:SetNear(cameraData.near)
        mainCamera:SetFar(cameraData.far)
        local offset = Vector3.New(tonumber(cameraData.camera_pos_offset_x), cameraData.camera_pos_offset_y, cameraData.camera_pos_offset_z)
        mainCamera:SetOffset(offset)
    end

    mainCamera:SetFollowTarget(followTarget)
    mainCamera:SetEnable(true)

end

local function SetStartTime(self, startTime)
    if self.mainCamera then
        self.mainCamera:SetCameraSmoothParam(startTime, smoothFlag)
    end
end

local function LateTick(self, delta)
    if not self.mainCamera then
        return
    end

    if not self.mainCamera:GetEnable() then
        return
    end

    CameraContext:GetInstance():LateTick(delta)
end

CameraManager.__init = __init
CameraManager.SetCamera = SetCamera
CameraManager.GetSmartCamera = GetSmartCamera
CameraManager.SetCameraAttribute = SetCameraAttribute
CameraManager.SetStartTime = SetStartTime
CameraManager.LateTick = LateTick

return CameraManager