---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2020/3/28 22:39
---

local SmartCamera = BaseClass("SmartCamera", TransformObject)
local base = TransformObject

local function __init(self)
    base.__init(self)
    self.camera = nil
    self.followTarget = nil
    self.dampingFactor = 16.0 --阻尼
    self.dampingAmplitude = 0.2 --阻尼振幅
    self.dampingFrequency = 8.0 --阻尼频率
    self.dampingDirection = Vector3.up  --阻尼方向
    self.followRelativeTargetPosition = true  --照射相对目标位置
    self.followRelativeTargetRotation = false --照射相对目标旋转角度
    self.followRelativeRotation = Quaternion.identity --照射相对目标旋转角度
    self.offset = Vector3.New()
    self.cutImageAgent = nil
    self.startTime = nil
    self.followDistance = 20
    self.enabled = false
end

local function SetCamera(self, camera)
    if self.camera ~= nil then
        self:DetachChild(self.camera.transform)
    end
    self.camera = camera
    if self.camera ~= nil then
        self:AttachChild(self.camera.transform)
    end
    self.enabled = true
end

local function GetCamera(self)
    return self.camera
end

local function Damping(self)
    self.dampingFactor = 16
    self.dampingAmplitude = 0.2
    self.dampingFrequency = 8.0
    self.dampingDirection = Vector3.up
end

local function SetEnable(self, enabled)
    if self.camera ~= nil then
        self.camera.enabled = enabled
        self.enabled = enabled
    end
end

local function GetEnable(self)
    if self.camera ~= nil then
        return self.enabled
    end
    return false
end

local function SetFollowTarget(self, target)
    self.followTarget = target
    if self.followTarget ~= nil then
        self.transform.position = target:GetWorldPosition() + self.offset
        local cameraContext = require "Camera.CameraContext":GetInstance()
        cameraContext:ChangeState(cameraContext:GetFollowState())
    end
end

local function GetFollowTarget(self)
    return self.followTarget
end

local function SetFov(self, fov)
    if self.camera ~= nil then
        self.camera.fieldOfView = fov
    end
end

local function GetFov(self)
    return self.camera.fieldOfView
end

local function SetNear(self, near)
    if self.camera ~= nil then
        self.camera.nearClipPlane = near
    end
end

local function GetNear(self)
    if self.camera ~= nil then
        return self.camera.nearClipPlane
    end
    return false
end

local function SetFar(self, far)
    if self.camera ~= nil then
        self.camera.farClipPlane = far
    end
end

local function GetFar(self)
    if self.camera ~= nil then
        return self.camera.farClipPlane
    end
    return false
end

local function SetBackgroundColor(self, color)
    if self.camera ~= nil then
        self.camera.backgroundColor = color
    end
end

local function GetBackgroundColor(self)
    if self.camera ~= nil then
        return self.camera.backgroundColor
    end
    return false
end

local function GetCutImageAgent(self)
    return self.cutImageAgent
end

local function SetOffset(self, offset)
    if offset then
        self.offset = offset
    end
end

local function GetOffset(self)
    return self.offset
end

local function SetStartTime(self, startTime)
    self.startTime = startTime
end

local function GetStartTime(self)
    return self.startTime
end

local function GetFollowDistance(self)
    return self.followDistance;
end

local function SetFollowDistance(self, followDistance)
    if followDistance then
        self.followDistance = followDistance
    end
end

SmartCamera.__init = __init
SmartCamera.SetCamera = SetCamera
SmartCamera.GetCamera = GetCamera
SmartCamera.Damping = Damping
SmartCamera.SetEnable = SetEnable
SmartCamera.GetEnable = GetEnable
SmartCamera.SetFollowTarget = SetFollowTarget
SmartCamera.GetFollowTarget = GetFollowTarget
SmartCamera.SetFov = SetFov
SmartCamera.GetFov = GetFov
SmartCamera.SetNear = SetNear
SmartCamera.GetNear = GetNear
SmartCamera.SetFar = SetFar
SmartCamera.GetFar = GetFar
SmartCamera.SetBackgroundColor = SetBackgroundColor
SmartCamera.GetBackgroundColor = GetBackgroundColor
SmartCamera.GetCutImageAgent = GetCutImageAgent
SmartCamera.SetOffset = SetOffset
SmartCamera.GetOffset = GetOffset
SmartCamera.SetStartTime = SetStartTime
SmartCamera.GetStartTime = GetStartTime
SmartCamera.GetFollowDistance = GetFollowDistance
SmartCamera.SetFollowDistance = SetFollowDistance

return SmartCamera;