---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ricashao.
--- DateTime: 2020/4/20 10:48
---
local BattleSkillUnit = BaseClass("BattleSkillUnit")

------------ private start -----------
local function InitBasicCfg(self)
    self.battler = BattleManager:GetInstance():GetBattle():FindBattlerByID(self.battlerId)
end
------------ private end   -----------

local function __init(self, battlerId, aimId, skillId, isLoop, unitResult, callback)
    self.battlerId = battlerId or 0
    self.skillId = skillId or 0
    self.isLoop = isLoop or false
    self.unitResult = unitResult --结果集合
    self.endCallback = callback
    self.aimId = aimId

    self.battler = nil
    self.eleSkillIds = {} --配表里包含元技能的ID 验证用
    self.elementSkills = {} --元技能
    self.effdatas = {} -- 持有的特效
    InitBasicCfg(self)
end

--开始技能演示
local function Show(self)
    local cfg = getInstance(SkillDB).getSkillCfgById(this.skillId)
    local ctx = require "Skills.SkillContext".New()
    --设置结果集
    ctx.unitResult = self:GetActionUnitResults()
    ctx.fighterId = self.battlerId
    ctx.skillConfig = cfg
    if (self.battler:GetCharacter() == nil) then
        Logger.Log(string.format("battler character == null %s ", self.battlerId))
    end
    ctx.caster = self.battler:GetCharacter()
    ctx.mainTarget = BattleManager:GetInstance():GetBattle():FindBattlerByID(self.aimId):GetCharacter()
    self.battler:GetCharacter():StartUnitAction(AttackAction.GetOperator(cfg.optype, ctx), false, BindCallback(self, self.OnActionEnd))
end

local function OnActionEnd(self)
    if (self.unitResult == nil or table.length(self.unitResult) == 0) then
        self.endCallback()
    else
        TimerManager:GetInstance():GetTimer(0.1, self.Show, self, true, false)
    end
end

local function GetActionUnitResults(self)
    local result = {}
    if (self.isLoop) then
        result.push(this.unitResult.shift())
    else
        for _, unit in ipairs(self.unitResult) do
            table.insert(result, unit)
        end
        self.unitResult = nil
    end
    return result
end

BattleSkillUnit.__init = __init
BattleSkillUnit.Show = Show
BattleSkillUnit.OnActionEnd = OnActionEnd
BattleSkillUnit.GetActionUnitResults = GetActionUnitResults

return BattleSkillUnit