---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ricashao.
--- DateTime: 2020/4/18 2:15
---
local BattleEffect = BaseClass("BattleEffect")

--绑定监听
local function StartRender(self)
    self._uRender:AddDBEventListener(CS.DragonBones.EventObject.COMPLETE, Bind(self, self.PlayComplete))
    self._uRender:AddDBEventListener(CS.DragonBones.EventObject.FRAME_EVENT, Bind(self, self.DispatchEvent))
    self:StartUnitAction()
end

local function PlayComplete(self)
    self.curLoop = self.curLoop + 1
    if (self.loop == 0) then
        self:StartUnitAction()
    elseif (self.loop == self.curLoop) then
        self:Delete()
    else
        self:StartUnitAction()
    end
end

local function DispatchEvent(self, type, eventObject)
    if (self.eventHandler) then
        self.eventHandler(eventObject.name, self)
    end
end

local function __init(self, uri, aniOption, create_callback, relative_order)
    self.relative_order = relative_order or 0
    local effect_config = EffectConfig[uri]
    self.loop = aniOption.loop or 1--循环次数
    self.curLoop = 0 -- 当前循环次数
    self.eventHandler = aniOption.handler

    if (effect_config == nil) then
        Logger.LogError("特效配置不存在 path：" .. uri)
    end

    self.effect = BaseEffect.New(self.transform, effect_config, function(pfb)
        if not IsNull(self.effect.gameObject) then
            local trans = self.effect.transform
            local rectTransform = UIUtil.FindComponent(trans, typeof(CS.UnityEngine.RectTransform))
            if not IsNull(rectTransform) then
                -- 初始化RectTransform
                rectTransform.offsetMax = Vector2.zero
                rectTransform.offsetMin = Vector2.zero
                rectTransform.localScale = Vector3.one
                rectTransform.localPosition = Vector3.zero
            end

            -- 获取龙骨
            self._uRender = pfb:GetComponent(typeof(CS.DragonBones.UnityArmatureComponent))
            StartRender(self)

            self:SetOrder(self.relative_order)
            if create_callback ~= nil then
                create_callback()
            end
        end
    end)
end

local function StartUnitAction(self)
    self._uRender:Play("idle")
end

local function __delete(self)
    self.effect:Delete()
    self.effect = nil
    self._uRender = nil
    self.eventHandler = nil
    self:Destroy()
end

BattleEffect.__init = __init
BattleEffect.StartUnitAction = StartUnitAction
BattleEffect.PlayComplete = PlayComplete
BattleEffect.DispatchEvent = DispatchEvent
BattleEffect.__delete = __delete
return BattleEffect
