--Generated By prototool Do not Edit
local config = {
	["CreateName_C2S_Msg"] = (require("Net.Protol.login_pb")).CreateName_C2S_Msg,
	["CreateName_S2C_Msg"] = (require("Net.Protol.login_pb")).CreateName_S2C_Msg,
	["EnterGame_C2S_Msg"] = (require("Net.Protol.login_pb")).EnterGame_C2S_Msg,
	["EnterGame_S2C_Msg"] = (require("Net.Protol.login_pb")).EnterGame_S2C_Msg,
	["ForceOffline_S2C_Msg"] = (require("Net.Protol.login_pb")).ForceOffline_S2C_Msg,
	["Login_C2S_Msg"] = (require("Net.Protol.login_pb")).Login_C2S_Msg,
	["Login_S2C_Msg"] = (require("Net.Protol.login_pb")).Login_S2C_Msg,
	["RandomName_C2S_Msg"] = (require("Net.Protol.login_pb")).RandomName_C2S_Msg,
	["RandomName_S2C_Msg"] = (require("Net.Protol.login_pb")).RandomName_S2C_Msg,
	["Regist_C2S_Msg"] = (require("Net.Protol.login_pb")).Regist_C2S_Msg,
	["Regist_S2C_Msg"] = (require("Net.Protol.login_pb")).Regist_S2C_Msg,
}
    return config