---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2020/3/27 23:56
---
local Fighter = BaseClass("Fighter")

local Application = CS.UnityEngine.Application
local Input = CS.UnityEngine.Input
local Physics = CS.UnityEngine.Physics
local EventSystem = CS.UnityEngine.EventSystems.EventSystem
local RectTransform = CS.UnityEngine.RectTransform

local FingerPhase = {
    Begin = 1,
    Move = 2,
    End = 3,
    None = 0,
}

-- 构造函数，别重写，初始化放OnInit
local function __init(self, camera)
    self.camera = camera
    self:OnCreate()
end

local function SetCamera(self, camera)
    self.camera = camera;
end

-- 创建：初始化一些需要全局保存的状态
local function OnCreate(self)
    self.phase = FingerPhase.None;

    self.pickedGameObject = nil
    self.currentSelectedGameObject = nil
    self.currentSelectedGameObjectRT = nil
    self.isOverUI = false

    self.startTime = 0
    self.holdTime = 0

    self.startPos = Vector2.zero
    self.pos = Vector2.zero
    self.endPos = Vector2.zero
    self.deltaPos = Vector2.zero
    self.fingerPos = Vector2.zero
    self.fingerDeltaPos = Vector2.zero

    self.isDrag = false
    self.triggerPress = false
end

local function RayCaster(self)
    local go = nil
    if Application.isPlaying and not IsNull(self.camera) then
        go = CS.RaycastUtils.RayCaster(self.camera)
    end
    return go
end

local function GetPickedInfo(self)
    self.pickedGameObject = self:RayCaster()
    self.isOverUI = not (InputTouch:GetInstance().isMobilePlatform and EventSystem.current:IsPointerOverGameObject(Input.GetTouch(0).fingerId) or EventSystem.current:IsPointerOverGameObject())
    self.currentSelectedGameObject = EventSystem.current.currentSelectedGameObject
    if not IsNull(self.currentSelectedGameObject) then
        self.currentSelectedGameObjectRT = self.currentSelectedGameObject:GetComponent(typeof(RectTransform));
    end
end

local function Tick(self)
    local inputTouch = InputTouch:GetInstance()
    local touchProxy = TouchProxy:GetInstance()
    -- 移动平台判断
    if (inputTouch.isMobilePlatform) then
        if (Input.touchCount <= 0) then
            self.phase = FingerPhase.None
        else
            local touch = Input.GetTouch(0)
            self.fingerPos = touch.position
            self.fingerDeltaPos = touch.deltaPosition
            if (touch.phase == TouchPhase.Began) then
                self.phase = FingerPhase.Begin
            elseif (touch.phase == TouchPhase.Moved) then
                self.phase = FingerPhase.Move
            elseif (touch.phase == TouchPhase.Ended) then
                self.phase = FingerPhase.End
            end
        end
    else
        self.fingerPos = Input.mousePosition
        self.fingerDeltaPos = Vector2.New(Input.GetAxis("Mouse X"), Input.GetAxis("Mouse Y"));

        self.phase = FingerPhase.None
        if (Input.GetMouseButtonDown(0)) then
            self.phase = FingerPhase.Begin
        elseif (Input.GetMouseButton(0)) then
            self.phase = FingerPhase.Move
        elseif (Input.GetMouseButtonUp(0)) then
            self.phase = FingerPhase.End
        end
    end
    if (self.phase == FingerPhase.None) then
        return
    end

    if (self.phase == FingerPhase.Begin) then
        self.isDrag = false;
        self.startPos = self.fingerPos
        self.endPos = self.fingerPos
        self.pos = self.fingerPos
        self.startTime = Time.realtimeSinceStartup

        self:GetPickedInfo()

        touchProxy:OnTouchDown(self)
    elseif self.phase == FingerPhase.Move then
        self.pos = self.ingerPos
        self.deltaPos = self.fingerDeltaPos

        if not (self.isDrag) then
            if self.deltaPos ~= Vector2.zero then
                self.isDrag = true
                self.startPos = pos
                touchProxy:OnTouchDragBegin(self)
            end

            --触发按住事件，时间阀值为0.500000011920929秒
            if not (triggerPress) then
                self.holdTime = Time.realtimeSinceStartup - self.startTime
                if (self.holdTime > 0.500000011920929) then
                    self.triggerPress = true;
                    touchProxy:OnTouchPress(self)
                end
            end
        else
            touchProxy:OnTouchDrag(self)

            -- 拖动后，如果获取的UI跟按住时的不一样，长按结束
            if (self.triggerPress
                    and self.currentSelectedGameObjectRT and self.camera
                    and not (CS.UnityEngine.RectTransformUtility.RectangleContainsScreenPoint(self.currentSelectedGameObjectRT, self.fingerPos, self.camera)))
            then
                self.triggerPress = false
                inputTouch:OnTouchPressEnd(self)
            end
        end
    elseif self.phase == FingerPhase.End then
        self.endPos = self.fingerPos
        touchProxy:OnTouchUp(self)

        self.holdTime = Time.realtimeSinceStartup - self.startTime

        if not self.isDrag then
            --按住事件结束
            if not self.triggerPress then
                self.triggerPress = false;
                touchProxy:OnTouchPressEnd(self)
            elseif (self.holdTime < 0.300000011920929) then
                -- 触发点击事件，时间阀值为0.300000011920929秒，和UGUI的点击事件判断时间相同
                touchProxy:OnTouchClick(self)
            end
        else
            self.isDrag = false
            touchProxy:OnTouchDragEnd(self)
        end
        self:InitFinger()
    end
end

local function InitFinger(self)
    self.phase = FingerPhase.None

    self.pickedGameObject = nil
    self.currentSelectedGameObject = null
    self.currentSelectedGameObjectRT = null
    self.isOverUI = false

    self.startTime = 0
    self.holdTime = 0

    self.startPos = Vector2.zero
    self.pos = Vector2.zero
    self.endPos = Vector2.zero
    self.deltaPos = Vector2.zero
    self.fingerPos = Vector2.zero
    self.fingerDeltaPos = Vector2.zero

    self.isDrag = false
    self.triggerPress = false
end

Fighter.__init = __init
Fighter.SetCamera = SetCamera
Fighter.OnCreate = OnCreate
Fighter.RayCaster = RayCaster
Fighter.GetPickedInfo = GetPickedInfo
Fighter.Tick = Tick
Fighter.InitFinger = InitFinger

return Fighter

