---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ricashao.
--- DateTime: 2020/4/16 15:03
---
local Warrior = BaseClass("Warrior", Character)

local function Parse(self, fightInfo, pos, dir)
    self.maxhp = fightInfo.maxhp
    self.hp = fightInfo.hp
    self.hide = false
end

local function Initialize(self, fighterInfo, pos, dir, cb)
    self:Parse(fighterInfo, pos, dir)
    self.layer = SceneLayer.Battler
    Character.Initialize(self, fighterInfo, pos, dir, cb)
end

local function GetType(self)
    return CHARACTER_TYPE.WARRIOR
end

------------ 移动相关 Begin -----------
--- 战斗中进行移动
local function MoveInBattle(self, movePaths, cb)
    local action = require "Unit.Actions.WalkSlgAction".New(movePaths)
    self:StartUnitAction(action, false, cb)
end

--- 被动移动时使用
local function MoveByTime(self, destpos, time, cb)

end

------------  移动相关 End   ----------

Warrior.MoveInBattle = MoveInBattle
Warrior.MoveByTime = MoveByTime
Warrior.Initialize = Initialize
Warrior.GetType = GetType
Warrior.Parse = Parse
return Warrior