---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ricashao.
--- DateTime: 2020/4/16 15:03
---
local Warrior = BaseClass("Warrior", Character)

local function Parse(self, fightInfo, pos, dir)
    self.maxhp = fightInfo.maxhp
    self.hp = fightInfo.hp
    self.hide = false
end

local function Initialize(self, fighterInfo, pos, dir, cb)
    this.parse(basicOctects, pos, dir)
    self.layer = SceneLayer.Battler
    Character.Initialize(self, fighterInfo, pos, dir, cb)
end

local function GetType(self)
    return CHARACTER_TYPE.WARRIOR
end

Warrior.Initialize = Initialize
Warrior.GetType = GetType
return Warrior