---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by admin.
--- DateTime: 2020/4/15 14:39
---
local Model = BaseClass("Model")

local function GetAllHandPoint(self, prefabRes)
    self.allHandPoint = {}
    self.allHandPointPositon = {}
    CharacterUtil.FindCharacterHand(prefabRes, self.allHandPoint)
    for k, v in pairs(self.allHandPoint) do
        self.allHandPointTransform[k] = v.transform
    end
end

local function InitModel(self)
    if not self.character then
        return
    end

    local prefabRes = self.character:GetPrefabRes()
    if not prefabRes then
        return
    end

    GetAllHandPoint(self, prefabRes)
end

local function __init(self, character)
    self.character = character
    self.allHandPoint = {}
    self.visible = false

    self.lastconditionName = ""
    self.activeConditions = nil
    self.allHandPointTransform = {}

    InitModel(self)
end

local function GetHandPos(self, name)
    if self.allHandPointTransform[name] ~= nil then
        return self.allHandPointTransform[name].position
    end
    return Vector3.zero
end

local function AddChild(self, name, child)
    if self.allHandPointTransform[name] ~= nil then
        child:SetParent(self.allHandPointTransform[name])
    end
end

Model.__init = __init
Model.GetHandPos = GetHandPos
Model.AddChild = AddChild

return Model