---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ricashao.
--- DateTime: 2020/4/18 0:20
---
local EfDecode = {}

function EfDecode.Decode(url)
    local arr = string.split(url, ":", 1, true)
    return {
        ef = arr[1],
        efType = arr[2],
        layer = arr[3],
        driction = arr[4],
    }
end

return EfDecode