---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by admin.
--- DateTime: 2020/4/16 16:33
---
local ClientBuffAgent = BaseClass("ClientBuffAgent")

local function __init(self, battler)
    self.battler = battler
    self.buffs = {}
end

local function InitBuff(self, key, value)
    local buff = { buffid = key, round = value }
    self:AddBuff(buff)
end

local function AddBuff(self, buff)
    self.buffs[buff.buffid] = buff
    --todo 隐身
    self.battler:AddEffectById(buff.buffid)
end

local function RefreshBuff(self, buff)
    self.buffs[buff.buffid].round = buff.round
end

local function RemoveBuff(self)
    local effectId = self.buffs[buffId];
    if effectId then
        self.battler:RemoveEffectById(effectId)
    end
    self.buffs[buffId] = nil
end

local function UpdateBuff(self, buff)
    if self.buffs[buff.buffid] then
        if buff.round == -1 then
            self:RemoveBuff(buff.buffid)
        else
            self:RefreshBuff(buff)
        end
    else
        self:AddBuff(buff);
    end
end

local function GetBuffs(self)
    return self.buffs
end

ClientBuffAgent.__init = __init
ClientBuffAgent.InitBuff = InitBuff
ClientBuffAgent.AddBuff = AddBuff
ClientBuffAgent.RefreshBuff = RefreshBuff
ClientBuffAgent.RemoveBuff = RemoveBuff
ClientBuffAgent.UpdateBuff = UpdateBuff
ClientBuffAgent.GetBuffs = GetBuffs
return ClientBuffAgent